info:
  contact: {}
  description: Give me request and I'll give you a power
  license:
    name: MIT
  title: Arcanery
  version: 0.0.1
paths:
  /{roomId}:
    get:
      consumes:
      - application/json
      description: Load frontend and start chat room
      operationId: RoomFront
      produces:
      - text/html
      responses: {}
      summary: Load frontend with websocket
      tags:
      - Frontend
  /new:
    get:
      consumes:
      - application/json
      description: Start chat room
      operationId: RoomBack
      produces:
      - application/json
      responses: {}
      summary: Create room
      tags:
      - Backend
  /rm/{roomId}:
    get:
      consumes:
      - application/json
      description: Remove room by id
      operationId: rmRoom
      produces:
      - text/html
      responses: {}
      summary: Delete Room
      tags:
      - del
swagger: "2.0"
